Add --import-guards option for cli.
rhys-vdw/ts-auto-guard pull request #125
Opened 2021-01-24 09:38 UTC by chrisczach

Add TypeGuard import and export to source file.

I have a library that I'm planning to use with ts-auto-guard. I'm adding the option on my fork to have the TypeGuards imported at the start of the file and exported as a named export at the end. But I thought it might be something that would be useful for others also.

2021-01-24 23:23 UTC, rhys-vdw commented
Ah, right. Um... I'm hesitant to add this because I like to keep code gen separated from hand-written code, and it also makes assumptions about project structure (that the types are exported from the file they're defined in, for example).

All that said, I've invited you as a collaborator now @chrisczach and if you think it's a useful feature, then I reckon let's merge it in. But not before *updating the docs and adding at least one test case*!

2021-01-24 23:24 UTC, rhys-vdw requested changes
- [x] Add at least one test
- [ ] Document new option with example in README.md

2021-01-24 23:37 UTC, chrisczach commented
Ok, I’ll add in documentation and test cases. Maybe I’ll update the —import-guards option to accept some configuration to be more flexible customizing the import alias and whether or not to export. Now that I think I about it. It’s probably best for the default, with no config, to only import but not export.

2021-01-25 03:24 UTC, rhys-vdw commented
> Now that I think I about it. It’s probably best for the default, with no config, to only import but not export.

@chrisczach that will cause unused imports, I think the export makes sense given the use case I'm imagining.

2021-01-25 05:04 UTC, chrisczach commented
@rhys-vdw  I'm having some trouble getting the test case to work. It's weird it's showing that the only errors are newlines, when I run it on an actual file the output looks as expected. Have you run into this before?
![image](https://user-images.githubusercontent.com/42812259/105663679-b7ab8800-5e87-11eb-9ff7-f89c9983ddc7.png)

2021-01-25 12:03 UTC, rhys-vdw commented
Okay, so the source file is outputting:
```ts
import * as CustomGuardAlias from "./test.guard";
    /** @see {isEmpty} ts-auto-guard:type-guard */
    export interface Empty {}
export { CustomGuardAlias };
```

And your "expected" value is evaluating to:
```ts
import * as CustomGuardAlias from "./test.guard";
/** @see {isEmpty} ts-auto-guard:type-guard */
export interface Empty { }
export { CustomGuardAlias };
```

I can't speak to the errors in the source, but the reason why you can't modify the expected text to match this is because it [gets forced through ts-morph's `formatText` function before being compared](https://github.com/rhys-vdw/ts-auto-guard/blob/10a6b88cc67efe1111e3118c5e4c6caa62836eed/tests/generate.ts#L66). The reason I do this is so that I don't have to worry about formatting the expected code property, as all the generate code is pushed through `formatText` so it's always going to be guaranteed to be the same.

So yeah, what's going on is that your test case is deeply indented by being part of this template literal:

```ts
`
    /** @see {isEmpty} ts-auto-guard:type-guard */
    export interface Empty {}`
```

And when add the statements in they are not indented (because that would be weird). So you end up with this mess of different indentations.

If you ensure the input string has the same formatting that ts-morph uses then you're sweet:

https://github.com/chrisczach/ts-auto-guard/pull/1

2021-01-25 16:11 UTC, chrisczach commented
Ah, that's what I missed. I had to apply the the formatting on the sourceFile also since it gets manipulated.

2021-01-25 22:59 UTC, rhys-vdw commented
@chrisczach you didn't use my PR? chrisczach#1 :-P

2021-01-25 23:26 UTC, chrisczach commented
@rhys-vdw Haha, oh man how did I miss that. I just merged it in and reverted the one where I applied .formatText() to the source.

2021-01-26 01:51 UTC, merged