Add MTS and CTS Support
rhys-vdw/ts-auto-guard pull request #244
Opened 2024-05-30 12:48 UTC by elliot-huffman

This PR adds `MTS` and `CTS` support for file output and input so that projects that use mixed module modes are supported.

Currently when an MTS or CTS file is used, the following error is encountered:
`Internal Error: sourcePath and outFilePath are identical: ...`

2024-06-03 15:39 UTC, rhys-vdw commented
Hi @elliot-huffman, this looks good to me.

Could you deduplicate the regex used for the file extensions? Declare it as a constant regex. Slight oversight, you've made one case insensitive but not the other. DRYing this would help such mistakes in future.

Also you'll need to prettier format for the tests to pass. You can `npm run format`.

Once this is merged I'll add you on as a collaborator if you would like it, so let me know.

2024-06-05 01:46 UTC, rhys-vdw requested changes

2024-06-05 01:46 UTC, rhys-vdw commented on src/index.ts
> +    /\.(ts|mts|cts|tsx|d\.ts)$/u,
This regex is case-insensitive

2024-06-05 01:46 UTC, rhys-vdw commented on src/index.ts
> +            .replace(/\.(ts|mts|cts|tsx|d\.ts)$/, '')
This one is the same, but is case sensitive.

2024-06-05 01:48 UTC, rhys-vdw commented
> QQ, when you say de-duplicate, I only have one Regex added to the script. What is it duplicating?

@elliot-huffman Sorry, I should have been more specific! I've added line comments. You didn't add the regexes, but you've caused them to deviate.

I would prefer to see:

```ts
// somewhere near top of file
const fileExtensionRegex = /\.(ts|mts|cts|tsx|d\.ts)$/u
```

To ensure that they keep in sync in future.

> I would love that!

Inviting you now.

2024-06-05 02:20 UTC, elliot-huffman commented
Updated, please check again :)

2024-06-05 06:13 UTC, rhys-vdw approved these changes

2024-06-05 06:14 UTC, merged

2024-06-05 06:14 UTC, rhys-vdw commented
Nice one.